In [2]:
import numpy as np

In [3]:
# Gerar um NDarray de 2x3 (Duas listas com 2 elementos aleatórios)
dados=np.random.rand(2,3)

In [4]:
# Print
dados

array([[0.13785876, 0.38808745, 0.45086515],
       [0.74136005, 0.19461004, 0.61309863]])

In [6]:
# Print tipo de dado gerado
dados.dtype

dtype('float64')

In [7]:
# Tamanho e quantidade de dimensões
dados.shape


(2, 3)

In [8]:
# Número de dimensões do Array
dados.ndim

2

In [11]:
# Criar um NDarray usando a função Array (Números float)
lista=(1.5, 2, 4, 5, 7.5)
dados2=np.array(lista)
dados2

array([1.5, 2. , 4. , 5. , 7.5])

In [14]:
# Criar um NDarray usando a função Array (Números Int)
lista2=[[1,2,3,4],[5,6,7,8]]
dados3=np.array(lista2)
lista2


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
# Outras maneiras de criar arrays
dadoszero=np.zeros(10)
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
dadoszero=np.zeros((2,3))
dadoszero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
dadossum=np.ones(5)
dadossum

array([1., 1., 1., 1., 1.])

In [20]:
# Cria 10 dados sequenciais
dadosseq=np.arange(15)
dadosseq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
# Cria um array de 0 a 20 de 2 em 2
dadosseq2=np.arange(0,20,2)
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
# Tranforma o tipo do dado
dadosseq.dtype

dadosseqf=dadosseq.astype(np.float64)

dadosseqf

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [25]:
# Aritmética com Array
dados4=np.array([[1,2,3],[4,5,6]])
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Multiplica o array
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [27]:
# Subtrai o array
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [28]:
# Divisão
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [29]:
# Somar e gerar uma nova estrutura 
dados5=dados4+dados4
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [31]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# Comparação
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

In [32]:
# Indexação
dadosseq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
# valor da Posição 
dadosseq[5]

5

In [34]:
# Define de qual valor começa e termina a posição
dadosseq[3:6]

array([3, 4, 5])

In [37]:
# Atribui um novo valor as posições
dadosseq[3:6]=20

In [36]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
# Fatia(recorta) a posição dos dados
fatiadados=dadosseq[2:4]
fatiadados

array([ 2, 20])

In [43]:
# Altera o valor 
fatiadados[1]=2000

In [41]:
fatiadados

array([   2, 2000])

In [42]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9,   10,
         11,   12,   13,   14])

In [47]:
fatiadados[:]=333
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [51]:
# Copiar dados sem broadcast
fatia2=dadosseq[2:3].copy()
fatia2

array([333])

In [49]:
fatia2[:]=111
fatia2

array([111])

In [50]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [55]:
# Array com mais de uma dimensão
dados6=np.array([[1,2,3], [4,5,6],[7,8,9]])
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
# Linha = 1, Coluna = 2
dados6[1,2]

6

In [56]:
# Máscaras
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [59]:
# Dados menores que 100
mascara=(dadosseq<100)

In [58]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [60]:
# Imprime dados menores que 20 e atribui 8888 nesses dados
dadosseq[dadosseq<20]=8888

In [61]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888, 8888,
       8888, 8888, 8888, 8888])

In [63]:
# Transposição: Cria 15 dados sequenciais na dimensão de 3x5 (linhas e colunas)  
dados7=np.arange(15).reshape((3,5))

In [64]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
# Inverte a transposição
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [68]:
# Multiplicação de Matrizes com Dots
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])